name: .NET Core CI

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Use .NET Core 3.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview8-013656

    - name: Restore, Build, Pack
      id: build_step
      run: dotnet pack -c Release -o publish

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Release
        path: publish
      if: (job.steps.build_step.status == success()) && (github.event_name != 'pull_request')
