name: .NET Core CI

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Use .NET Core 3.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview8-013656

    - name: Restore, Build, Pack
      run: dotnet pack -c Release -o publish

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Release
        path: publish
      if: success() && (github.event_name != 'pull_request')

    - name: Test Step 1
      run: echo %TEST_VALUE%
      env:
        TEST_VALUE: ${{ github.ref }}

    - name: Test Step 2
      run: echo Partial ref matches!
      if: startsWith(github.ref, 'v')

    - name: Test Step 3
      run: echo Full ref matches!
      if: startsWith(github.ref, 'refs/tags/v')
