name: .NET Core CI

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Use .NET Core 3.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview8-013656

    - name: Restore, Build, Pack
      id: build_step
      run: dotnet pack -c Release -o publish

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Release
        path: publish
      #if: (job.steps.build_step.status == success()) && (github.event_name != 'pull_request')
      if: success() && (github.event_name != 'pull_request')

    - name: NuGet Push
      run: dotnet nuget push .\publish\*.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      #if: (job.steps.build_step.status == success()) && (github.event_name != 'pull_request') && startsWith(github.ref, 'refs/tags/v')
      if: success() && (github.event_name != 'pull_request') && startsWith(github.ref, 'refs/tags/v')

    - name: Draft Release
      uses: softprops/action-gh-release@v0.1.0
      with:
        draft: true
        files: publish\*.nupkg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: success() && (github.event_name != 'pull_request') && startsWith(github.ref, 'refs/tags/v')
